import type { Theme } from "./tokens";

export const paperTheme: Theme = {
  id: "paper",
  name: "Paper",
  appearance: "light",
  tokens: {
    "bg":            "#F7F4EC",
    "bg-alt":        "#EFEADD",
    "bg-elevated":   "#FFFDF7",
    "bg-hover":      "#EDE7DD",
    "fg":            "#181712",
    "fg-muted":      "#8F8A7B",
    "border":        "#E0DBCA",
    "accent":        "#134E4A",
    "accent-fg":     "#FFFDF7",
    "accent-strong": "#0D3B38",
    "error":         "#E5484D",
    // muted sage-stone — replaces saturated amber; chart tertiary stays in warm-neutral family
    "warn":          "#7A8F8B",
    "ok":            "#134E4A",
    "selection-bg":  "rgba(19, 78, 74, 0.12)",
    "selection-fg":  "#1C1C1C",
    "cursor":        "#1C1C1C",

    "ansi-0":  "#1C1C1C",
    "ansi-1":  "#E5484D",
    "ansi-2":  "#134E4A",
    "ansi-3":  "#7A8F8B",
    "ansi-4":  "#134E4A",
    "ansi-5":  "#7C3AED",
    "ansi-6":  "#5BA8A3",
    "ansi-7":  "#FBF8F5",
    "ansi-8":  "#8E8883",
    "ansi-9":  "#FF6166",
    "ansi-10": "#6BC2BB",
    "ansi-11": "#8FA89B",
    "ansi-12": "#4A8B86",
    "ansi-13": "#A78BFA",
    "ansi-14": "#7ED3CC",
    "ansi-15": "#FFFFFF",
  },
};
